### ISSUE TITLE
Is this project still active ?

### ISSUE THREAD

**Issue by Mehdi-YC** [togettoyou/kubectl-lazy#1]
Hello , i wanted to say thank you to the dev , and at the same time , why no one is using this tool ? it looks good and reminds me of one of the best project im using  "lazydocker"

**Comment by togettoyou** [comment]
Hi @Mehdi-YC . Thank you for your approval, in fact this project was inspired by lazydocker to build.

But this project is really too rudimentary now, it is only used as my personal daily use. It is not very likely to continue to be updated.

**Comment by Mehdi-YC** [comment]
i understand , but i guess if there is a change in kubectl , you will update it , right ?
